//const loggerobj = require ('./logger')
//const helperobj = require('./util/helper')
//const changeToLowerCase1 = require ('./util/validator/formatter')
//const obj = require('lodash')


//loggerobj.logging('module system')
//loggerobj.printWelcomeMessage()
//console.log(loggerobj.loggerEndpoint)
//console.log('------------------------------')
//helperobj.getDate1()
//helperobj.getMonth1()
//helperobj.getBatchInfo1()
//console.log('---------------------------------')
//formatterobj.trim()
//changeToLowerCase1.changeToLowercase()
 //changetoUpperrCase1.changeToUppercase()
//console.log('------------------------------------')
console.log(obj.tail(1,3,7,9,11,13,15,17,19))
console.log(obj.chunk(["January","February","March","April","May","June","July","August","September","October","November","Decemeber"]))
console.log(obj.union([1,2,3],[3,4,5],[4,5,6]))
console.log(obj.fromPairs(["honor","The shining"],["drama","titanic"],["thriller","shutter"],["fantastic,crazy"]))